### PR TITLE
Synchronize panes

### PR DESCRIPTION
**Pull request by O-Zone**
@davidgrove73 @xenma @siglun @naderak 

Finally this is the synchronized panes wich points to the new version of the KbOSD! :-) It should work now! :dancer: :-D

### CODE REVIEW

**Comment by siglun** [comment]
+0.95. The synchronized paging works nicely

+0.05 If you fix the following:
There are two arrows to the left and two towards the right when browsing in full screen mode.

I'll give you one more point if you can synchronize the page numbers in the OSD with the one in the text (available from the snippet server upon a request from the project leads ;^)

**Comment by O-Zone** [comment]
Nicely spotted Sigge - there IS a problem with turning off the original OpenSeadragon arrows in the new version og kbOpenSeadragon! :) (I'm happy it isn't in production yet)
I will fix it, but getting the fix in production will require Peter to push a new version into "production", so it might not happen right away.

**Comment by xenma** [comment]
Other than that, I think :+1:

**Comment by O-Zone** [comment]
@siglun : I can't change the OSD pagenumbers without changing the KbOSD. I should be possible to add a new config option like "pageNumberOffset" that is added to the shown page number, but I already do manipulate that number because of the rtl option (that only kbOSD have, not OSD), so it might be a tiny bit complicated. (but for that extra one point I will definitely give it a try! ;-D)
Will you be able to set the correct offset in the config object? (you can do it already even if it does not work - it will just be ignored if not understood)

**Comment by O-Zone** [comment]
Oh yeah - and to complicate things further, OSD operates on a zero based pagenumber, while kbOSD operates with a one based pagenumber.

As I recall it, I do have a pageNumberNormalizer object that I have crammed all the gory details into - that might come in handy for the pageNumerOffset option, since all pageNumbers goes through that object? :-) (If I remember correctly)

**Pull request merged**
