### PR TITLE
Erorr pages

### PR DESCRIPTION
**Pull request by naderak**
For testing it in development environment mode, you have to change "Exception Handler" configuration. For it, Find config.rb in exception_handler Gem folder (/lib/exception_handler/config.rb) and change:
dev: 	  false,
to:
dev: 	  true,  
It is not the correct way but the fastest! ;-)
Then you can try these link:
For 500: 
http://localhost:3000/catalog/%2Fletter_books%2F001541111%2F001541111_000-L0015411110
For Page not find
http://localhost:3000/blabla.html

### CODE REVIEW

**Comment by siglun** [comment]
I don't understand what's going on in this one... Is it
 app/views/exception_handler/exception/show.html.erb 
or the error files  such as public/404.html which does the job?

Sigge

**Comment by naderak** [comment]
You don’t need any file in public folder.

app/views/exception_handler/exception/show.html.erb  do all jobs.

Mvh.
-Nader

Fra: Sigfrid Lundberg [mailto:notifications@github.com]
Sendt: 25. august 2016 12:48
Til: Det-Kongelige-Bibliotek/Danmarks-Breve
Cc: Nader Khatibi; Author
Emne: Re: [Det-Kongelige-Bibliotek/Danmarks-Breve] Erorr pages (#69)


I don't understand what's going on in this one... Is it
app/views/exception_handler/exception/show.html.erb
or the error files such as public/404.html which does the job?

Sigge

**Comment by Weinkouff** [comment]
We need the 500 and 404 pages themselves to look nice and clean when you hit them

**Comment by naderak** [comment]
Herby the images for 500 and 404.

-Nader



Fra: Weinkouff [mailto:notifications@github.com]
Sendt: 25. august 2016 12:51
Til: Det-Kongelige-Bibliotek/Danmarks-Breve
Cc: Nader Khatibi; Author
Emne: Re: [Det-Kongelige-Bibliotek/Danmarks-Breve] Erorr pages (#69)


We need the 500 and 404 pages themselves to look nice and clean when you hit them

**Comment by siglun** [comment]
+1 Then I'm fine with this patch, if we remove the error pages from public which are still in the pull request ;^)

Sigge

**Comment by naderak** [comment]
I removed them from my branch and expected that they will be removed in github too!

-Nader

Fra: Sigfrid Lundberg [mailto:notifications@github.com]
Sendt: 25. august 2016 13:02
Til: Det-Kongelige-Bibliotek/Danmarks-Breve
Cc: Nader Khatibi; Author
Emne: Re: [Det-Kongelige-Bibliotek/Danmarks-Breve] Erorr pages (#69)


+1 Then I'm fine with this patch, if we remove the error pages from public which are still in the pull request ;^)

Sigge

**Pull request merged**
